//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{DateTime, Utc, serde::ts_seconds};
use sea_orm::{ActiveValue, IntoActiveModel, RelationTrait, entity::prelude::*};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "hint")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  #[serde(with = "ts_seconds")]
  pub created_at: DateTime<Utc>,
  pub challenge_id: i64,
  #[sea_orm(column_type = "Text")]
  pub content: String,
  /// Use score to unlock this hint.
  pub cost: i32,
}

impl Model {
  pub fn desensitize(self) -> Self {
    Self {
      content: String::new(),
      ..self
    }
  }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::challenge::Entity",
    from = "Column::ChallengeId",
    to = "super::challenge::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Challenge,
  #[sea_orm(has_many = "super::extra::Entity")]
  Extra,
}

impl Related<super::challenge::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Challenge.def()
  }
}

impl Related<super::extra::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Extra.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_list<C>(db: &C, challenge_id: i64) -> Result<Vec<Model>, DbErr>
where
  C: ConnectionTrait,
{
  Entity::find()
    .filter(Column::ChallengeId.eq(challenge_id))
    .all(db)
    .await
}

pub async fn get<C>(db: &C, hint_id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait,
{
  Entity::find_by_id(hint_id).one(db).await
}

pub async fn create<C>(db: &C, hint: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait,
{
  let hint = ActiveModel {
    id: ActiveValue::NotSet,
    created_at: ActiveValue::Set(Utc::now()),
    ..hint.into_active_model().reset_all()
  };
  hint.insert(db).await
}

pub async fn delete<C>(db: &C, hint_id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait,
{
  Entity::delete_by_id(hint_id).exec(db).await.map(|_| ())
}

// #[cfg(test)]
// mod tests {
//     use super::get_list;
//     use sea_orm::{ConnectOptions, Database, DatabaseConnection};

//     #[tokio::test]
//     async fn test_get_hints() {
//         let mut connect_options = ConnectOptions::new(
//             // development only
//
// "postgresql://ret2shell:P@ssw02dInD3v3l0pm3nt@localhost:5432/ret2shell",
//         );
//         connect_options.acquire_timeout(std::time::Duration::from_secs(15));

//         let db: DatabaseConnection =
// Database::connect(connect_options).await.unwrap();         println!("{:?}",
// get_list(&db, 1, false).await.unwrap());     }
// }
