//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{Utc, serde::ts_seconds};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user2_ip")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub user_id: i64,
  pub ip_address_id: i64,
  #[serde(with = "ts_seconds")]
  pub last_active_at: chrono::DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::ip::Entity",
    from = "Column::IpAddressId",
    to = "super::ip::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Ip,
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::UserId",
    to = "super::user::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  User,
}

impl Related<super::ip::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Ip.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
