//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::entity::prelude::*;

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize, Serializer};
use serde_repr::{Deserialize_repr, Serialize_repr};

pub fn to_option_ts<S>(time: &Option<DateTime<Utc>>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    match time {
        Some(time) => to_ts(time, serializer),
        None => serializer.serialize_none(),
    }
}

pub fn from_option_ts<'de, D>(deserializer: D) -> Result<Option<DateTime<Utc>>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let time = Option::<DateTime<Utc>>::deserialize(deserializer)?;
    Ok(time)
}

#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Serialize_repr,
    Deserialize_repr,
    EnumIter,
    DeriveActiveEnum,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(u8)]
#[sea_orm(rs_type = "u8", db_type = "Integer")]
pub enum Status {
    #[default]
    Pending = 0,
    Running = 1,
    Success = 2,
    Error = 3,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "action")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub created_at: DateTime<Utc>,
    #[serde(deserialize_with = "from_option_ts", serialize_with = "to_option_ts")]
    pub started_at: Option<DateTime<Utc>>,
    pub challenge_id: i64,
    pub status: Status,
    pub commit_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Challenge,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
