//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use sea_orm::ActiveValue;

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, TimeZone, Utc};
use sea_query::Condition;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "calendar")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub intro: String,
    pub link: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub start_time: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub end_time: DateTime<Utc>,
    pub audited: bool,
    pub game_id: Option<i64>,
    pub reporter_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Game,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ReporterId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_calendar_list(
    conn: &DatabaseConnection,
    start_time: i64,
    end_time: i64,
) -> Result<Vec<Model>, DbErr> {
    let start_time = Utc
        .timestamp_opt(start_time, 0)
        .single()
        .ok_or(DbErr::Custom("invalid timestamp of start_time".to_owned()))?;
    let end_time = Utc
        .timestamp_opt(end_time, 0)
        .single()
        .ok_or(DbErr::Custom("invalid timestamp of end_time".to_owned()))?;
    let models = Entity::find()
        .filter(
            Condition::any()
                .add(
                    Condition::all()
                        .add(Column::StartTime.gt(start_time))
                        .add(Column::StartTime.lt(end_time)),
                )
                .add(
                    Condition::all()
                        .add(Column::EndTime.gt(start_time))
                        .add(Column::EndTime.lt(end_time)),
                ),
        )
        .all(conn)
        .await?;
    Ok(models)
}

pub async fn create_calendar(conn: &DatabaseConnection, calendar: Model) -> Result<Model, DbErr> {
    let mut active_model: ActiveModel = calendar.into();
    active_model.id = ActiveValue::NotSet;
    active_model.insert(conn).await
}

pub async fn update_calendar(
    conn: &DatabaseConnection,
    id: i64,
    calendar: Model,
) -> Result<Model, DbErr> {
    let mut active_model: ActiveModel = calendar.clone().into();
    active_model.id = ActiveValue::Unchanged(id);
    active_model.name = ActiveValue::Set(calendar.name);
    active_model.intro = ActiveValue::Set(calendar.intro);
    active_model.link = ActiveValue::Set(calendar.link);
    active_model.start_time = ActiveValue::Set(calendar.start_time);
    active_model.end_time = ActiveValue::Set(calendar.end_time);
    active_model.audited = ActiveValue::Set(calendar.audited);
    active_model.game_id = ActiveValue::Set(calendar.game_id);
    active_model.reporter_id = ActiveValue::Set(calendar.reporter_id);
    active_model.update(conn).await
}

pub async fn delete_calendar(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(conn).await.map(|_| ())
}
