//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use sea_orm::{ActiveValue, IntoActiveModel, QuerySelect};

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, TimeZone, Utc};
use sea_orm::Iterable;
use sea_query::Condition;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "calendar")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub intro: Option<String>,
    pub link: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub start_time: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub end_time: DateTime<Utc>,
    pub reporter_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ReporterId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_calendar_list(
    conn: &DatabaseConnection,
    start_time: i64,
    end_time: i64,
) -> Result<Vec<Model>, DbErr> {
    let start_time = Utc
        .timestamp_opt(start_time, 0)
        .single()
        .ok_or(DbErr::Custom("invalid timestamp of start_time".to_owned()))?;
    let end_time = Utc
        .timestamp_opt(end_time, 0)
        .single()
        .ok_or(DbErr::Custom("invalid timestamp of end_time".to_owned()))?;
    let models = Entity::find()
        .select_only()
        .columns(Column::iter().filter(|c| !matches!(c, Column::Intro)))
        .filter(
            Condition::any()
                .add(
                    Condition::all()
                        .add(Column::StartTime.gt(start_time))
                        .add(Column::StartTime.lt(end_time)),
                )
                .add(
                    Condition::all()
                        .add(Column::EndTime.gt(start_time))
                        .add(Column::EndTime.lt(end_time)),
                )
                .add(
                    Condition::all()
                        .add(Column::StartTime.lt(start_time))
                        .add(Column::EndTime.gt(end_time)),
                ),
        )
        .all(conn)
        .await?;
    Ok(models)
}

pub async fn get_calendar_by_id(conn: &DatabaseConnection, id: i64) -> Result<Model, DbErr> {
    Entity::find_by_id(id)
        .one(conn)
        .await?
        .ok_or(DbErr::RecordNotFound("calendar".to_owned()))
}

pub async fn create_calendar(conn: &DatabaseConnection, calendar: Model) -> Result<Model, DbErr> {
    let mut active_model: ActiveModel = calendar.into();
    active_model.id = ActiveValue::NotSet;
    active_model.insert(conn).await
}

pub async fn update_calendar(
    conn: &DatabaseConnection,
    id: i64,
    calendar: Model,
) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::Unchanged(id),
        ..calendar.into_active_model().reset_all()
    };
    active_model.update(conn).await
}

pub async fn delete_calendar(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(conn).await.map(|_| ())
}
