//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use sea_orm::{ActiveValue, IntoActiveModel, Iterable, QueryOrder, QuerySelect};

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use super::user::Permission;
use super::{game, submission, user};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "challenge")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub content: Option<String>,
    pub hidden: bool,
    pub game_id: i64,
    pub tag_id: i64,
    pub initial_score: i32,
    pub current_score: i32,
    pub minimum_score: i32,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub updated_at: DateTime<Utc>,
    pub decay: i32,
    pub bucket: Option<String>,
    pub checker: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::action::Entity")]
    Action,
    #[sea_orm(has_many = "super::answer::Entity")]
    Answer,
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Game,
    #[sea_orm(has_many = "super::hint::Entity")]
    Hint,
    #[sea_orm(has_many = "super::instance::Entity")]
    Instance,
    #[sea_orm(has_many = "super::plan2_challenge::Entity")]
    Plan2Challenge,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
    #[sea_orm(
        belongs_to = "super::tag::Entity",
        from = "Column::TagId",
        to = "super::tag::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Tag,
}

impl Related<super::action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl Related<super::answer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Answer.def()
    }
}

impl Related<game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::hint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hint.def()
    }
}

impl Related<super::instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instance.def()
    }
}

impl Related<super::plan2_challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plan2Challenge.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn create_challenge(conn: &DatabaseConnection, challenge: Model) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        updated_at: ActiveValue::Set(Utc::now()),
        current_score: ActiveValue::Set(challenge.initial_score),
        ..challenge.into_active_model().reset_all()
    };
    active_model.insert(conn).await
}

pub async fn update_challenge(
    conn: &DatabaseConnection,
    id: i64,
    challenge: Model,
) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::Unchanged(id),
        updated_at: ActiveValue::Set(Utc::now()),
        checker: ActiveValue::NotSet,
        current_score: ActiveValue::NotSet,
        bucket: ActiveValue::NotSet,
        game_id: ActiveValue::NotSet,
        ..challenge.into_active_model().reset_all()
    };
    active_model.update(conn).await
}

pub async fn get_challenge(conn: &DatabaseConnection, id: i64) -> Result<Model, DbErr> {
    let challenge = Entity::find_by_id(id).one(conn).await?;
    match challenge {
        Some(challenge) => Ok(challenge),
        None => Err(DbErr::RecordNotFound("challenge".to_string())),
    }
}

pub async fn get_challenge_page_by_game_and_user(
    conn: &DatabaseConnection,
    game: game::Model,
    user: user::Model,
    page: u64,
    per_page: u64,
) -> Result<(Vec<Model>, u64), DbErr> {
    let can_see_hidden_challenges = match (user.institute_id, game.institute_id) {
        (Some(user_institute_id), Some(game_institute_id)) => {
            (user_institute_id == game_institute_id
                && user.permissions.0.contains(&Permission::Organize))
                || user.permissions.0.contains(&Permission::Devops)
        }
        _ => user.permissions.0.contains(&Permission::Devops),
    };
    let mut sql = Entity::find()
        .select_only()
        .filter(Column::GameId.eq(game.id))
        .columns(Column::iter().filter(|c| !matches!(c, Column::Content | Column::Bucket)))
        .order_by_desc(Column::Id);
    if !can_see_hidden_challenges {
        sql = sql.filter(Column::Hidden.eq(false));
    }
    let paginator = sql.into_model().paginate(conn, per_page);
    let num_pages = paginator.num_pages().await?;
    let challenges = paginator.fetch_page(page - 1).await?;
    Ok((challenges, num_pages))
}

pub async fn delete_challenge(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    // TODO: delete related data and repo folder
    Entity::delete_by_id(id).exec(conn).await.map(|_| ())
}

pub async fn calc_challenge_score(
    conn: &DatabaseConnection,
    game: &game::Model,
    challenge: &Model,
) -> Result<i32, DbErr> {
    let solves = get_challenge_solves_in_game(conn, challenge, game).await?;
    let score = _calc_challenge_score(challenge, solves);
    Ok(score)
}

async fn get_challenge_solves_in_game(
    conn: &DatabaseConnection,
    challenge: &Model,
    game: &game::Model,
) -> Result<u64, DbErr> {
    let solves = challenge
        .find_related(submission::Entity)
        .filter(submission::Column::Solved.eq(true))
        .filter(submission::Column::CreatedAt.gt(game.start_time))
        .filter(submission::Column::CreatedAt.lt(game.end_time))
        .distinct_on([
            (submission::Entity, submission::Column::UserId),
            (submission::Entity, submission::Column::ChallengeId),
        ])
        .count(conn)
        .await?;
    Ok(solves)
}

fn _calc_challenge_score(challenge: &Model, solves: u64) -> i32 {
    let mut score = if challenge.decay == 0 {
        challenge.initial_score
    } else {
        (((solves * solves) as f64 / (challenge.decay * challenge.decay) as f64)
            * (challenge.minimum_score - challenge.initial_score) as f64
            + challenge.initial_score as f64)
            .round() as i32
    };
    if score < challenge.minimum_score {
        score = challenge.minimum_score;
    }
    score
}

pub async fn update_challenge_current_score(
    conn: &DatabaseConnection,
    challenge: &Model,
) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::Unchanged(challenge.id),
        current_score: ActiveValue::Set(challenge.current_score),
        ..challenge.clone().into()
    };
    Ok(active_model.update(conn).await?)
}
