//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use sea_orm::{ActiveValue, IntoActiveModel, Iterable, QueryOrder, QuerySelect};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub updated_at: DateTime<Utc>,
    pub name: String,
    pub brief: String,
    #[sea_orm(column_type = "Text")]
    pub introduction: Option<String>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub start_time: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub end_time: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub register_time: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub archive_time: DateTime<Utc>,
    pub hidden: bool,
    pub frozen: bool,
    pub host_as_game: bool,
    pub team_size_limit: i32,
    pub cover_path: String,
    pub enable_team_audit: bool,
    pub can_register_after_started: bool,
    pub institute_id: Option<i64>,
}

impl Model {
    pub fn in_progress(&self) -> bool {
        let now = Utc::now();
        self.start_time <= now && now <= self.end_time
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::calendar::Entity")]
    Calendar,
    #[sea_orm(has_many = "super::challenge::Entity")]
    Challenge,
    #[sea_orm(
        belongs_to = "super::institute::Entity",
        from = "Column::InstituteId",
        to = "super::institute::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Institute,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::team::Entity")]
    Team,
    #[sea_orm(has_many = "super::write_up::Entity")]
    WriteUp,
}

impl Related<super::calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendar.def()
    }
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::institute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institute.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl Related<super::write_up::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WriteUp.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_game(conn: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(id).one(conn).await
}

pub async fn create_game(conn: &DatabaseConnection, game: Model) -> Result<(), DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        updated_at: ActiveValue::Set(Utc::now()),
        ..game.into_active_model().reset_all()
    };
    active_model.insert(conn).await?;
    Ok(())
}

/// get game list with paginator params.
///
/// ## Arguments
///
/// * `conn` - Database connection
/// * `page` - Page number
/// * `per_page` - Number of items per page
/// * `host_as_game` - Whether the game will be hosted as a `Game`, or it will be treated as `Playground`, which is open to all users.
/// * `filter_hidden` - Whether to filter hidden games
pub async fn get_game_page(
    conn: &DatabaseConnection,
    page: u64,
    per_page: u64,
    host_as_game: Option<bool>,
    filter_hidden: bool,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find()
        .select_only()
        .columns(Column::iter().filter(|c| !matches!(c, Column::Introduction)))
        .order_by_desc(Column::StartTime);
    if let Some(host_as_game) = host_as_game {
        sql = sql.filter(Column::HostAsGame.eq(host_as_game));
    } else {
        // returns games by default
        sql = sql.filter(Column::HostAsGame.eq(true));
    }
    if filter_hidden {
        sql = sql.filter(Column::Hidden.eq(false));
    }
    let paginator = sql.into_model().paginate(conn, per_page);
    let resp = paginator.fetch_page(page - 1).await?;
    let num_pages = paginator.num_pages().await?;
    Ok((resp, num_pages))
}

pub async fn update_game(conn: &DatabaseConnection, id: i64, game: Model) -> Result<(), DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::Unchanged(id),
        updated_at: ActiveValue::Set(Utc::now()),
        ..game.into_active_model().reset_all()
    };
    active_model.update(conn).await?;
    Ok(())
}
