//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use sea_orm::QueryOrder;

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "instance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub addr: String,
    #[sea_orm(unique)]
    pub wsrx: String,
    pub flag: String,
    pub renew_count: i32,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub started_at: DateTime<Utc>,
    pub user_id: Option<i64>,
    pub challenge_id: i64,
    pub running: bool,
}

impl Model {
    pub fn should_stop(&self) -> bool {
        self.started_at.timestamp() + ((self.renew_count * 3600) as i64) < Utc::now().timestamp()
    }
    pub fn desentialize(&self) -> Self {
        Self {
            addr: String::new(),
            flag: String::new(),
            ..self.clone()
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Challenge,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_instance_by_user_id(
    conn: &DatabaseConnection,
    user_id: i64,
) -> Result<Option<Model>, DbErr> {
    let instance = Entity::find()
        .filter(Column::UserId.eq(user_id))
        .order_by_desc(Column::StartedAt)
        .one(conn)
        .await?;

    Ok(instance.map_or_else(
        || None,
        |inst| {
            if !inst.should_stop() && inst.running {
                Some(inst)
            } else {
                None
            }
        },
    ))
}

pub async fn get_instance_by_wsrx(
    conn: &DatabaseConnection,
    wsrx: &str,
) -> Result<Option<Model>, DbErr> {
    let instance = Entity::find()
        .filter(Column::Wsrx.eq(wsrx))
        .one(conn)
        .await?;

    Ok(instance)
}
