//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::{entity::prelude::*, ActiveValue};
use serde::{Deserialize, Serialize};

use super::{prelude::User2IpAddress, user2_ip_address};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ip_address")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user2_ip_address::Entity")]
    User2IpAddress,
}

impl Related<super::user2_ip_address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2IpAddress.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_ip_address::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_ip_address::Relation::IpAddress.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
pub async fn link_to_user(
    conn: &DatabaseConnection,
    user_id: i64,
    ip_address: &str,
) -> anyhow::Result<()> {
    let last_insert_id = match Entity::find()
        .filter(Column::Address.eq(ip_address))
        .one(conn)
        .await
    {
        Ok(Some(data)) => data.id,
        _ => {
            let model = ActiveModel {
                id: ActiveValue::NotSet,
                address: ActiveValue::Set(ip_address.to_string()),
            };
            Entity::insert(model).exec(conn).await?.last_insert_id
        }
    };
    match User2IpAddress::find()
        .filter(user2_ip_address::Column::UserId.eq(user_id))
        .filter(user2_ip_address::Column::IpAddressId.eq(last_insert_id))
        .count(conn)
        .await
    {
        Ok(0) => (),
        _ => return Ok(()),
    }
    User2IpAddress::insert(user2_ip_address::ActiveModel {
        id: ActiveValue::NotSet,
        user_id: ActiveValue::Set(user_id),
        ip_address_id: ActiveValue::Set(last_insert_id),
    })
    .exec(conn)
    .await?;
    Ok(())
}
