//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ip_address")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user2_ip_address::Entity")]
    User2IpAddress,
}

impl Related<super::user2_ip_address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2IpAddress.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
