//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod action;
pub mod announcement;
pub mod answer;
pub mod calendar;
pub mod challenge;
pub mod cheat_record;
pub mod config;
pub mod extra;
pub mod game;
pub mod hint;
pub mod instance;
pub mod institute;
pub mod ip_address;
pub mod media;
pub mod notification;
pub mod oauth;
pub mod plan;
pub mod plan2_challenge;
pub mod submission;
pub mod subscription;
pub mod tag;
pub mod team;
pub mod user;
pub mod user2_ip_address;
pub mod user2_subscription;
pub mod user2_team;
pub mod wiki;
pub mod write_up;
