//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plan")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub price: i64,
    pub duration: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::plan2_challenge::Entity")]
    Plan2Challenge,
}

impl Related<super::plan2_challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plan2Challenge.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
