//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use chrono::{
    serde::ts_seconds::{deserialize as from_ts, serialize as to_ts},
    DateTime, Utc,
};
use sea_orm::{
    entity::prelude::*, ActiveValue, FromQueryResult, IntoActiveModel, QueryOrder, QuerySelect,
};
use sea_query::JoinType;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "submission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub created_at: DateTime<Utc>,
    pub user_id: i64,
    pub challenge_id: i64,
    pub team_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub solved: bool,
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ModelWithInfo {
    pub id: i64,
    pub user_id: i64,
    pub challenge_id: i64,
    pub game_id: i64,
    pub tag_id: i64,
    pub challenge_score: i32,
    pub user_name: String,
    pub challenge_name: String,
    pub tag_name: String,
    pub content: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub created_at: DateTime<Utc>,
    pub solved: bool,
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ModelOnlyUserInfo {
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub created_at: DateTime<Utc>,
    pub user_id: i64,
    pub user_name: String,
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ModelOnlyTeamInfo {
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub created_at: DateTime<Utc>,
    pub team_id: i64,
    pub team_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Challenge,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::TeamId",
        to = "super::team::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Team,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_submission_page(
    conn: &DatabaseConnection, challenge_id: Option<i64>, game_id: Option<i64>, page: u64,
    per_page: u64,
) -> Result<(Vec<ModelWithInfo>, u64), DbErr> {
    let mut sql = Entity::find();
    sql = sql
        .join(JoinType::InnerJoin, Relation::Challenge.def())
        .join(JoinType::InnerJoin, Relation::User.def())
        .join(JoinType::InnerJoin, super::challenge::Relation::Tag.def());
    sql = sql
        .column(Column::Content)
        .column(Column::Solved)
        .column_as(super::challenge::Column::Name, "challenge_name")
        .column_as(super::user::Column::Name, "user_name")
        .column_as(super::challenge::Column::GameId, "game_id")
        .column_as(super::challenge::Column::TagId, "tag_id")
        .column_as(super::challenge::Column::CurrentScore, "challenge_score")
        .column_as(super::tag::Column::Name, "tag_name")
        .order_by_desc(Column::CreatedAt);
    if let Some(challenge_id) = challenge_id {
        sql = sql.filter(Column::ChallengeId.eq(challenge_id));
    }
    if let Some(game_id) = game_id {
        sql = sql.filter(super::challenge::Column::GameId.eq(game_id));
    }
    let paginator = sql.into_model().paginate(conn, per_page);
    let resp = paginator.fetch_page(page - 1).await?;
    let num_pages = paginator.num_pages().await?;
    Ok((resp, num_pages))
}

pub async fn get_solved_submission_of_team(
    conn: &DatabaseConnection, game_id: i64, team_id: i64,
) -> Result<Vec<ModelWithInfo>, DbErr> {
    let mut sql = Entity::find();
    sql = sql
        .join(JoinType::InnerJoin, Relation::Challenge.def())
        .join(JoinType::InnerJoin, Relation::User.def())
        .join(JoinType::InnerJoin, super::challenge::Relation::Tag.def())
        .filter(super::challenge::Column::GameId.eq(game_id))
        .filter(Column::Solved.eq(true))
        .filter(Column::TeamId.eq(team_id))
        .distinct_on([(Entity, Column::TeamId), (Entity, Column::ChallengeId)])
        .distinct_on([(Entity, Column::UserId), (Entity, Column::ChallengeId)]);

    let sql = sql
        .column_as(super::challenge::Column::Name, "challenge_name")
        .column_as(super::user::Column::Name, "user_name")
        .column_as(super::challenge::Column::GameId, "game_id")
        .column_as(super::challenge::Column::TagId, "tag_id")
        .column_as(super::challenge::Column::CurrentScore, "challenge_score")
        .column_as(super::tag::Column::Name, "tag_name");
    // .order_by_desc(Column::CreatedAt);
    // F**k you SQL.
    let mut resp = sql.into_model::<ModelWithInfo>().all(conn).await?;
    resp.sort_by(|a, b| a.created_at.cmp(&b.created_at));
    Ok(resp)
}

pub async fn get_solved_submission_of_user(
    db: &DatabaseConnection, game_id: i64, user_id: i64,
) -> Result<Vec<Model>, DbErr> {
    let mut sql = Entity::find();
    sql = sql
        .join(JoinType::InnerJoin, Relation::Challenge.def())
        .filter(Column::UserId.eq(user_id))
        .filter(Column::Solved.eq(true))
        .filter(super::challenge::Column::GameId.eq(game_id))
        .distinct_on([(Entity, Column::UserId), (Entity, Column::ChallengeId)]);
    sql.into_model().all(db).await
}

pub async fn create_submission(
    conn: &DatabaseConnection, submission: Model,
) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        created_at: ActiveValue::Set(Utc::now()),
        ..submission.into_active_model().reset_all()
    };
    active_model.insert(conn).await
}

pub async fn check_team_solved(
    conn: &DatabaseConnection, challenge_id: i64, team_id: i64,
) -> Result<bool, DbErr> {
    let sql = Entity::find()
        .filter(Column::ChallengeId.eq(challenge_id))
        .filter(Column::TeamId.eq(team_id))
        .filter(Column::Solved.eq(true))
        .one(conn)
        .await?;
    Ok(sql.is_some())
}

pub async fn get_solved_user_page(
    conn: &DatabaseConnection, challenge_id: i64, page: u64, per_page: u64,
) -> Result<(Vec<ModelOnlyUserInfo>, u64), DbErr> {
    let sql = Entity::find()
        .select_only()
        .columns([Column::Id, Column::UserId, Column::CreatedAt])
        .join(JoinType::InnerJoin, Relation::User.def())
        .column_as(super::user::Column::Name, "user_name")
        .filter(Column::ChallengeId.eq(challenge_id))
        .filter(Column::Solved.eq(true))
        .distinct_on([(Entity, Column::UserId), (Entity, Column::ChallengeId)]);
    let paginator = sql
        .into_model::<ModelOnlyUserInfo>()
        .paginate(conn, per_page);
    let mut resp = paginator.fetch_page(page - 1).await?;
    resp.sort_by(|a, b| a.created_at.cmp(&b.created_at));
    let num_pages = paginator.num_pages().await?;
    Ok((resp, num_pages))
}

pub async fn get_solved_team_page(
    conn: &DatabaseConnection, challenge_id: i64, page: u64, per_page: u64,
) -> Result<(Vec<ModelOnlyTeamInfo>, u64), DbErr> {
    let sql = Entity::find()
        .select_only()
        .columns([Column::Id, Column::TeamId, Column::CreatedAt])
        .join(JoinType::InnerJoin, Relation::Team.def())
        .column_as(super::team::Column::Name, "team_name")
        .filter(Column::TeamId.is_not_null())
        .filter(Column::ChallengeId.eq(challenge_id))
        .filter(Column::Solved.eq(true))
        .distinct_on([(Entity, Column::TeamId), (Entity, Column::ChallengeId)]);
    let paginator = sql
        .into_model::<ModelOnlyTeamInfo>()
        .paginate(conn, per_page);
    let mut resp = paginator.fetch_page(page - 1).await?;
    resp.sort_by(|a, b| a.created_at.cmp(&b.created_at));
    let num_pages = paginator.num_pages().await?;
    Ok((resp, num_pages))
}

pub async fn count_solves(conn: &DatabaseConnection, challenge_id: i64) -> Result<u64, DbErr> {
    Entity::find()
        .filter(Column::ChallengeId.eq(challenge_id))
        .filter(Column::Solved.eq(true))
        .filter(Column::TeamId.is_not_null())
        .distinct_on([(Entity, Column::TeamId), (Entity, Column::ChallengeId)])
        .distinct_on([(Entity, Column::UserId), (Entity, Column::ChallengeId)])
        .count(conn)
        .await
}

pub async fn count_submissions(
    conn: &DatabaseConnection, challenge_id: i64, solved: Option<bool>,
) -> Result<u64, DbErr> {
    let mut sql = Entity::find().filter(Column::ChallengeId.eq(challenge_id));
    if let Some(solved) = solved {
        sql = sql.filter(Column::Solved.eq(solved));
    }

    sql.count(conn).await
}
