//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "subscription")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub plan_id: i64,
    pub subscriber_id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub start_time: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user2_subscription::Entity")]
    User2Subscription,
}

impl Related<super::user2_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Subscription.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
