//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::{entity::prelude::*, ActiveValue, IntoActiveModel};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::challenge::Entity")]
    Challenge,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_tag_list(conn: &DatabaseConnection) -> Result<Vec<Model>, DbErr> {
    let tags = Entity::find().all(conn).await?;
    Ok(tags)
}

pub async fn create_tag(conn: &DatabaseConnection, tag: Model) -> Result<Model, DbErr> {
    let tag = ActiveModel {
        id: ActiveValue::NotSet,
        ..tag.into_active_model().reset_all()
    };
    tag.insert(conn).await
}

pub async fn delete_tag(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    let tag = Entity::find_by_id(id).one(conn).await?;
    match tag {
        Some(tag) => tag.delete(conn).await.map(|_| ()),
        None => Err(DbErr::RecordNotFound("tag".to_string())),
    }
}
