//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use std::collections::HashSet;

use chrono::{
    serde::ts_seconds::{deserialize as from_ts, serialize as to_ts},
    DateTime, Utc,
};
use nanoid::{alphabet, nanoid};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{
    entity::prelude::*, ActiveValue, FromJsonQueryResult, FromQueryResult, IntoActiveModel,
    QueryOrder, QuerySelect,
};
use sea_query::{Condition, Func, JoinType};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use super::{
    extra,
    user::{self, Entity as User},
};

#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Serialize_repr,
    Deserialize_repr,
    EnumIter,
    DeriveActiveEnum,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(i32)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum State {
    Banned = 0,
    #[default]
    NeedAudit = 1,
    Normal = 2,
    Hidden = 3,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistory {
    pub score: i32,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub time: DateTime<Utc>,
    pub challenge_id: Option<i64>,
    pub blood_state: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistoryList(pub Vec<TeamScoreHistory>);

impl TeamScoreHistoryList {
    pub fn new() -> Self {
        Self(vec![TeamScoreHistory {
            time: Utc::now(),
            ..Default::default()
        }])
    }
}
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub game_id: i64,
    pub token: Option<String>,
    pub state: State,
    pub institute_id: Option<i64>,
    pub score: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub history: TeamScoreHistoryList,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub last_active_at: DateTime<Utc>,
}

#[derive(FromQueryResult, Serialize)]
pub struct ModelWithGameName {
    pub id: i64,
    pub name: String,
    pub game_id: i64,
    pub game_name: String,
    pub state: State,
    pub institute_id: Option<i64>,
    pub score: i32,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub last_active_at: DateTime<Utc>,
}

impl Model {
    pub fn desensitize(&self) -> Self {
        Self {
            token: Some(String::new()),
            ..self.clone()
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
    #[sea_orm(
        belongs_to = "super::institute::Entity",
        from = "Column::InstituteId",
        to = "super::institute::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Institute,
    #[sea_orm(has_many = "super::cheat_record::Entity")]
    CheatRecord,
    #[sea_orm(has_many = "super::write_up::Entity")]
    WriteUp,
    #[sea_orm(has_many = "super::user2_team::Entity")]
    User2Team,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::institute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institute.def()
    }
}

impl Related<super::cheat_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheatRecord.def()
    }
}

impl Related<super::write_up::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WriteUp.def()
    }
}

impl Related<super::user2_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Team.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl Related<user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_team::Relation::User.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::user2_team::Relation::Team.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_scoreboard(
    conn: &DatabaseConnection, game_id: i64, page: u64, per_page: u64, all: Option<bool>,
    institute: Option<i64>,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .order_by_desc(Column::Score)
        .order_by_asc(Column::LastActiveAt);
    if let Some(institute) = institute {
        sql = sql.filter(Column::InstituteId.eq(institute));
    }
    match all {
        Some(true) => sql = sql.filter(Column::State.gte(State::Normal)),
        _ => sql = sql.filter(Column::State.eq(State::Normal)),
    }
    let paginator = sql.paginate(conn, per_page);
    let num_pages = paginator.num_pages().await?;
    let teams = paginator.fetch_page(page - 1).await?;
    let teams = teams.into_iter().map(|team| team.desensitize()).collect();
    Ok((teams, num_pages))
}

pub async fn get_team_members(
    conn: &DatabaseConnection, id: i64,
) -> Result<Vec<user::Model>, DbErr> {
    let team = Entity::find_by_id(id).one(conn).await?;
    if let Some(team) = team {
        let users = team.find_related(user::Entity).all(conn).await?;
        let mut users: Vec<user::Model> =
            users.into_iter().map(|user| user.desensitize()).collect();
        users.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(users)
    } else {
        Err(DbErr::RecordNotFound("user".to_string()))
    }
}

pub async fn get_team_by_user_id(
    conn: &DatabaseConnection, game_id: i64, user_id: i64,
) -> Result<Option<Model>, DbErr> {
    let (_, team): (user::Model, Option<Model>) = match user::Entity::find_by_id(user_id)
        .find_also_related(Entity)
        .filter(Column::GameId.eq(game_id))
        .one(conn)
        .await?
    {
        Some((user, team)) => (user, team),
        None => {
            return Ok(None);
        }
    };
    Ok(team)
}

#[derive(FromQueryResult)]
struct ChallengeScore {
    score: i32,
}

async fn calc_team_score(
    conn: &DatabaseConnection, team: &Model, game_id: i64,
) -> Result<i32, DbErr> {
    let mut sql = super::submission::Entity::find()
        .filter(super::submission::Column::TeamId.eq(team.id))
        .filter(super::submission::Column::Solved.eq(true));
    sql = sql
        .join(
            JoinType::InnerJoin,
            super::submission::Relation::Challenge.def(),
        )
        .filter(super::challenge::Column::GameId.eq(game_id))
        .filter(super::challenge::Column::Hidden.eq(false))
        .select_only()
        .column_as(super::challenge::Column::CurrentScore, "score")
        .distinct_on([
            (super::submission::Entity, super::submission::Column::TeamId),
            (
                super::submission::Entity,
                super::submission::Column::ChallengeId,
            ),
        ])
        .distinct_on([
            (super::submission::Entity, super::submission::Column::UserId),
            (
                super::submission::Entity,
                super::submission::Column::ChallengeId,
            ),
        ]);
    let res = sql.into_model::<ChallengeScore>().all(conn).await?;
    let mut team_score = 0;
    for challenge_score in res {
        team_score += challenge_score.score
    }
    let extras = extra::get_extras_by_team_id(conn, team.id).await?;
    for extra in extras {
        team_score += extra.score;
    }
    Ok(team_score)
}

pub async fn update_team_score(
    conn: &DatabaseConnection, team: &Model, game_id: i64, last_active_at: DateTime<Utc>,
) -> Result<i32, DbErr> {
    let team_score = calc_team_score(conn, team, game_id).await?;
    let mut active_model = team.clone().into_active_model();
    active_model.score = ActiveValue::Set(team_score);
    active_model.last_active_at = ActiveValue::Set(last_active_at);
    active_model.update(conn).await?;
    Ok(team_score)
}

pub async fn get_team_page_by_game_id(
    conn: &DatabaseConnection, game_id: i64, page: u64, per_page: u64, filter: Option<String>,
    need_audit: Option<bool>,
) -> Result<(Vec<Model>, u64), DbErr> {
    let sql = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .order_by_asc(Column::Id);
    let mut sql = filter_team(sql, filter)?;
    if Some(true) == need_audit {
        sql = sql.filter(Column::State.eq(State::NeedAudit));
    }
    let paginator = sql.paginate(conn, per_page);
    let num_pages = paginator.num_pages().await?;
    let teams = paginator.fetch_page(page - 1).await?;
    let teams = teams.into_iter().map(|team| team.desensitize()).collect();
    Ok((teams, num_pages))
}

fn filter_team(mut sql: Select<Entity>, filter: Option<String>) -> Result<Select<Entity>, DbErr> {
    if let Some(filter) = filter {
        let mut cond = Condition::any();
        if let Ok(num) = filter.parse::<i64>() {
            cond = cond.add(Column::Id.eq(num));
            cond = cond.add(Column::State.eq(num));
        }
        let filter = format!("%{}%", filter.to_ascii_lowercase());
        cond = cond.add(Expr::expr(Func::lower(Expr::col(Column::Name))).like(filter.clone()));
        sql = sql.filter(cond);
    };
    Ok(sql)
}

pub async fn create_team(conn: &DatabaseConnection, team: Model) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        token: ActiveValue::set(Some(nanoid!(21, &alphabet::SAFE))),
        last_active_at: ActiveValue::set(Utc::now()),
        ..team.into_active_model().reset_all()
    };
    let resp = active_model.insert(conn).await?;
    Ok(resp)
}

pub async fn get_team_by_game_id_and_name(
    conn: &DatabaseConnection, game_id: i64, name: &str,
) -> Result<Option<Model>, DbErr> {
    let res = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .filter(Column::Name.eq(name))
        .one(conn)
        .await?;
    Ok(res)
}

pub async fn get_team_rank_by_user_id(
    conn: &DatabaseConnection, game_id: i64, user_id: i64,
) -> Result<Option<u64>, DbErr> {
    let team = get_team_by_user_id(conn, game_id, user_id).await?;
    let team = match team {
        Some(team) => team,
        None => {
            return Ok(None);
        }
    };
    let res = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .filter(Column::State.eq(State::Normal))
        .filter(
            Condition::any().add(Column::Score.gt(team.score)).add(
                Condition::all()
                    .add(Column::Score.eq(team.score))
                    .add(Column::LastActiveAt.lt(team.last_active_at)),
            ),
        )
        .count(conn)
        .await?;
    Ok(Some(res + 1))
}

pub async fn get_team_rank_by_id(
    conn: &DatabaseConnection, game_id: i64, id: i64,
) -> Result<Option<u64>, DbErr> {
    let team = get_team(conn, id).await?;
    let team = match team {
        Some(team) => team,
        None => {
            return Ok(None);
        }
    };
    let res = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .filter(Column::State.eq(State::Normal))
        .filter(
            Condition::any().add(Column::Score.gt(team.score)).add(
                Condition::all()
                    .add(Column::Score.eq(team.score))
                    .add(Column::LastActiveAt.lt(team.last_active_at)),
            ),
        )
        .count(conn)
        .await?;
    Ok(Some(res + 1))
}

pub async fn get_team(conn: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
    let res = Entity::find_by_id(id).one(conn).await?;
    Ok(res)
}
pub async fn update_team(conn: &DatabaseConnection, id: i64, team: Model) -> Result<(), DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::Unchanged(id),
        game_id: ActiveValue::NotSet,
        token: ActiveValue::NotSet,
        score: ActiveValue::NotSet,
        history: ActiveValue::NotSet,
        last_active_at: ActiveValue::NotSet,
        ..team.into_active_model().reset_all()
    };
    active_model.update(conn).await.map(|_| ())
}

pub async fn get_team_by_token(
    conn: &DatabaseConnection, token: &str,
) -> Result<Option<Model>, DbErr> {
    let res = Entity::find()
        .filter(Column::Token.eq(token))
        .one(conn)
        .await?;
    Ok(res)
}

pub async fn get_teams_by_user_id(
    conn: &DatabaseConnection, user_id: i64,
) -> Result<Vec<ModelWithGameName>, DbErr> {
    let res = Entity::find()
        .join(JoinType::InnerJoin, Relation::User2Team.def())
        .join(JoinType::InnerJoin, Relation::Game.def())
        .column_as(super::game::Column::Name, "game_name")
        .filter(super::user2_team::Column::UserId.eq(user_id))
        .into_model::<ModelWithGameName>()
        .all(conn)
        .await?;
    Ok(res)
}

pub async fn get_affected_teams_by_challenge_id(
    conn: &DatabaseConnection, challenge_id: i64,
) -> Result<Vec<Model>, DbErr> {
    let submissions = super::submission::Entity::find()
        .filter(super::submission::Column::ChallengeId.eq(challenge_id))
        .filter(super::submission::Column::Solved.eq(true))
        .all(conn)
        .await?;
    let mut team_ids = HashSet::new();
    let mut teams: Vec<Model> = Vec::new();
    for submission in submissions {
        // let user = submission.find_related(User).one(conn).await?;
        let team = submission
            .find_related(User)
            .find_also_related(Entity)
            .one(conn)
            .await?
            .ok_or(DbErr::RecordNotFound("team".to_string()))?
            .1;
        if let Some(team) = team {
            if !team_ids.contains(&team.id) {
                team_ids.insert(team.id);
                teams.push(team);
            }
        }
    }
    Ok(teams)
}

pub async fn update_team_history(conn: &DatabaseConnection, team: &Model) -> Result<(), DbErr> {
    let mut active_model = team.clone().into_active_model();
    active_model.history = ActiveValue::Set(team.history.clone());
    active_model.update(conn).await.map(|_| ())
}
