//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{entity::prelude::*, FromJsonQueryResult};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Serialize_repr,
    Deserialize_repr,
    EnumIter,
    DeriveActiveEnum,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(u8)]
#[sea_orm(rs_type = "u8", db_type = "Integer")]
pub enum State {
    Banned = 0,
    #[default]
    NeedAudit = 1,
    Normal = 2,
    Hidden = 3,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistory {
    pub score: i32,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub time: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Default, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistoryList(Vec<TeamScoreHistory>);

impl TeamScoreHistoryList {
    pub fn new() -> Self {
        Self(vec![TeamScoreHistory {
            score: 0,
            time: Utc::now(),
        }])
    }
}
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub game_id: i64,
    pub token: Option<String>,
    pub state: State,
    pub institute_id: Option<i64>,
    pub score: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub history: TeamScoreHistoryList,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub last_active_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
    #[sea_orm(
        belongs_to = "super::institute::Entity",
        from = "Column::InstituteId",
        to = "super::institute::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Institute,
    #[sea_orm(has_many = "super::user2_team::Entity")]
    User2Team,
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::institute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institute.def()
    }
}

impl Related<super::user2_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Team.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
