//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{
    entity::prelude::*, ActiveValue, FromJsonQueryResult, IntoActiveModel, Iterable, QueryOrder,
    QuerySelect,
};
use sea_query::{Condition, Func, Order};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};
use std::str::FromStr;

use super::ip_address;

#[derive(
    FromPrimitive, ToPrimitive, Clone, Copy, Debug, PartialEq, Serialize_repr, Deserialize_repr, Eq,
)]
#[repr(i32)]
pub enum Permission {
    Basic,
    Verified,
    Publish,
    Audit,
    Organize,
    Devops,
    Statistics,
    Calendar,
    Certificates,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Permissions(pub Vec<Permission>);

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    #[serde(skip_serializing)]
    pub password: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub intro: Option<String>,
    pub cover_path: Option<String>,
    pub institute_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub institute_info: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub permissions: Permissions,
    pub hidden: bool,
    pub banned: bool,
}

impl Model {
    pub fn desensitize(&self) -> Self {
        Self {
            password: None,
            email: None,
            institute_info: None,
            ..self.clone()
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::announcement::Entity")]
    Announcement,
    #[sea_orm(has_many = "super::answer::Entity")]
    Answer,
    #[sea_orm(has_many = "super::calendar::Entity")]
    Calendar,
    #[sea_orm(has_many = "super::instance::Entity")]
    Instance,
    #[sea_orm(
        belongs_to = "super::institute::Entity",
        from = "Column::InstituteId",
        to = "super::institute::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Institute,
    #[sea_orm(has_many = "super::media::Entity")]
    Media,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
    #[sea_orm(has_many = "super::user2_ip_address::Entity")]
    User2IpAddress,
    #[sea_orm(has_many = "super::user2_subscription::Entity")]
    User2Subscription,
    #[sea_orm(has_many = "super::user2_team::Entity")]
    User2Team,
    #[sea_orm(has_many = "super::wiki::Entity")]
    Wiki,
    #[sea_orm(has_many = "super::write_up::Entity")]
    WriteUp,
}

impl Related<super::announcement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Announcement.def()
    }
}

impl Related<super::answer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Answer.def()
    }
}

impl Related<super::calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendar.def()
    }
}

impl Related<super::instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instance.def()
    }
}

impl Related<super::institute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institute.def()
    }
}

impl Related<super::media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Media.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl Related<super::user2_ip_address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2IpAddress.def()
    }
}

impl Related<super::user2_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Subscription.def()
    }
}

impl Related<super::user2_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Team.def()
    }
}

impl Related<super::wiki::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wiki.def()
    }
}

impl Related<super::write_up::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WriteUp.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_team::Relation::Team.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_team::Relation::User.def().rev())
    }
}

impl Related<super::ip_address::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_ip_address::Relation::IpAddress.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_ip_address::Relation::User.def().rev())
    }
}

impl Related<super::subscription::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_subscription::Relation::Subscription.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_subscription::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[allow(dead_code)]
pub async fn get_user(db: &DatabaseConnection, id: i64) -> Result<Model, DbErr> {
    let user = Entity::find_by_id(id).one(db).await?;
    match user {
        Some(user) => Ok(user),
        None => Err(DbErr::RecordNotFound("user".to_string())),
    }
}

pub async fn get_user_by_account(db: &DatabaseConnection, account: &str) -> Result<Model, DbErr> {
    let user = Entity::find()
        .filter(
            Condition::any()
                .add(Column::Name.eq(account))
                .add(Expr::expr(Func::lower(Expr::col(Column::Email))).eq(account.to_lowercase())),
        )
        .one(db)
        .await?;
    match user {
        Some(user) => Ok(user),
        None => Err(DbErr::RecordNotFound("user".to_string())),
    }
}

pub async fn get_ip_address_of_user(
    conn: &DatabaseConnection,
    user_id: i64,
) -> Result<Vec<ip_address::Model>, DbErr> {
    let user = Entity::find()
        .filter(Column::Id.eq(user_id))
        .one(conn)
        .await?;
    match user {
        Some(user) => Ok(user.find_related(ip_address::Entity).all(conn).await?),
        None => Err(DbErr::RecordNotFound("user".to_string())),
    }
}

pub async fn create_user(db: &DatabaseConnection, user: Model) -> Result<Model, DbErr> {
    let active_model: ActiveModel = ActiveModel {
        id: ActiveValue::NotSet,
        ..user.into_active_model().reset_all()
    };
    active_model.insert(db).await
}

pub async fn count_user(db: &DatabaseConnection) -> Result<u64, DbErr> {
    Entity::find().count(db).await
}

pub async fn get_user_page(
    db: &DatabaseConnection,
    page: u64,
    per_page: u64,
    order: Option<String>,
    filter: Option<String>,
    op_user: &Model,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find()
        .select_only()
        .columns(Column::iter().filter(|col| {
            !matches!(
                col,
                Column::Password | Column::InstituteInfo | Column::Intro
            )
        }));
    let mut cond = Condition::any().add(Column::Hidden.eq(false));
    if op_user.permissions.0.contains(&Permission::Organize) {
        cond = cond.add(Column::InstituteId.eq(op_user.institute_id));
    }
    if op_user.permissions.0.contains(&Permission::Devops) {
        cond = cond.add(Column::Hidden.eq(true));
    }
    sql = sql.filter(cond);
    let sql = filter_and_order_user(sql, order, filter)?;
    let paginator = sql.into_model().paginate(db, per_page);
    let num_pages = paginator.num_pages().await?;
    let mut users: Vec<Model> = paginator.fetch_page(page - 1).await?;
    if !op_user.permissions.0.contains(&Permission::Organize)
        && !op_user.permissions.0.contains(&Permission::Devops)
    {
        users = users
            .into_iter()
            .map(|mut user| {
                user.institute_id = None;
                user.email = None;
                user
            })
            .collect();
    }
    Ok((users, num_pages))
}

fn filter_and_order_user(
    mut sql: Select<Entity>,
    order: Option<String>,
    filter: Option<String>,
) -> Result<Select<Entity>, DbErr> {
    if let Some(filter) = filter {
        let mut cond = Condition::any();
        if let Ok(id) = filter.parse::<i64>() {
            cond = cond.add(Column::Id.eq(id));
        }
        let filter = format!("%{}%", filter.to_ascii_lowercase());
        cond = cond.add(Expr::expr(Func::lower(Expr::col(Column::Name))).like(filter.clone()));
        cond = cond.add(Expr::expr(Func::lower(Expr::col(Column::Email))).like(filter.clone()));
        sql = sql.filter(cond);
    };
    if let Some(order) = order {
        let order = order.split(',').collect::<Vec<&str>>();
        for o in order {
            let mut is_desc = true;
            let o = match o.starts_with('-') {
                true => &o[1..],
                false => {
                    is_desc = false;
                    o
                }
            };
            let col = match Column::from_str(o) {
                Ok(col) => col,
                Err(_) => return Err(DbErr::Custom("invalid order column".to_string())),
            };
            match is_desc {
                true => sql = sql.order_by(col, Order::Desc),
                false => sql = sql.order_by(col, Order::Asc),
            }
        }
    };
    Ok(sql)
}

pub async fn update_user(db: &DatabaseConnection, id: i64, user: Model) -> Result<Model, DbErr> {
    let active_model: ActiveModel = ActiveModel {
        id: ActiveValue::Unchanged(id),
        password: ActiveValue::NotSet,
        ..user.into_active_model().reset_all()
    };
    active_model.update(db).await
}

pub async fn update_self_profile(
    db: &DatabaseConnection,
    id: i64,
    user: Model,
) -> Result<Model, DbErr> {
    let active_model: ActiveModel = ActiveModel {
        id: ActiveValue::Unchanged(id),
        email: ActiveValue::NotSet,
        password: ActiveValue::NotSet,
        institute_id: ActiveValue::NotSet,
        institute_info: ActiveValue::NotSet,
        hidden: ActiveValue::NotSet,
        banned: ActiveValue::NotSet,
        permissions: ActiveValue::NotSet,
        ..user.into_active_model().reset_all()
    };
    active_model.update(db).await
}

pub async fn delete_user(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await?;
    Ok(())
}

pub async fn update_user_password(db: &DatabaseConnection, id: i64, password: String) -> Result<Model, DbErr> {
    match Entity::find_by_id(id).one(db).await? {
        Some(user) => {
            let mut active_model: ActiveModel = user.into();
            active_model.id = ActiveValue::Unchanged(id);
            active_model.password = ActiveValue::Set(Some(password));
            Ok(active_model.update(db).await?)
        }
        None => Err(DbErr::RecordNotFound("user".to_string())),
    }
}

#[cfg(test)]
mod test {
    use sea_orm::IntoActiveModel;

    use super::*;
    #[test]
    fn test_model_transform() {
        let model = Model {
            id: 0,
            name: String::from("Reverier"),
            password: Some(String::from("123456")),
            email: Some(String::from("reverier.xu@woooo.tech")),
            intro: Some(String::from("123456")),
            cover_path: None,
            institute_id: None,
            institute_info: None,
            permissions: Permissions(vec![Permission::Basic]),
            hidden: false,
            banned: false,
        };

        let active_model: ActiveModel = model.clone().into_active_model().reset_all();

        println!("{:?}", active_model);
    }
}
