//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{entity::prelude::*, ActiveValue, FromJsonQueryResult, IntoActiveModel};
use sea_query::{Condition, Func};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(
    FromPrimitive, ToPrimitive, Clone, Copy, Debug, PartialEq, Serialize_repr, Deserialize_repr, Eq,
)]
#[repr(u8)]
pub enum Permission {
    Basic,
    Verified,
    Publish,
    Audit,
    Organize,
    Devops,
    Statistics,
    Calendar,
    Certificates,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Permissions(pub Vec<Permission>);

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub password: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub intro: Option<String>,
    pub cover_path: Option<String>,
    pub institute_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub institute_info: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub permissions: Permissions,
    pub hidden: bool,
    pub banned: bool,
}

impl Model {
    pub fn desensitize(&self) -> Self {
        Self {
            password: None,
            email: None,
            ..self.clone()
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::announcement::Entity")]
    Announcement,
    #[sea_orm(has_many = "super::answer::Entity")]
    Answer,
    #[sea_orm(has_many = "super::calendar::Entity")]
    Calendar,
    #[sea_orm(has_many = "super::instance::Entity")]
    Instance,
    #[sea_orm(
        belongs_to = "super::institute::Entity",
        from = "Column::InstituteId",
        to = "super::institute::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Institute,
    #[sea_orm(has_many = "super::media::Entity")]
    Media,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
    #[sea_orm(has_many = "super::user2_ip_address::Entity")]
    User2IpAddress,
    #[sea_orm(has_many = "super::user2_subscription::Entity")]
    User2Subscription,
    #[sea_orm(has_many = "super::user2_team::Entity")]
    User2Team,
    #[sea_orm(has_many = "super::wiki::Entity")]
    Wiki,
    #[sea_orm(has_many = "super::write_up::Entity")]
    WriteUp,
}

impl Related<super::announcement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Announcement.def()
    }
}

impl Related<super::answer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Answer.def()
    }
}

impl Related<super::calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendar.def()
    }
}

impl Related<super::instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instance.def()
    }
}

impl Related<super::institute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institute.def()
    }
}

impl Related<super::media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Media.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl Related<super::user2_ip_address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2IpAddress.def()
    }
}

impl Related<super::user2_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Subscription.def()
    }
}

impl Related<super::user2_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Team.def()
    }
}

impl Related<super::wiki::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wiki.def()
    }
}

impl Related<super::write_up::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WriteUp.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[allow(dead_code)]
pub async fn get_user(db: &DatabaseConnection, id: i64) -> Result<Model, DbErr> {
    let user = Entity::find_by_id(id).one(db).await?;
    match user {
        Some(user) => Ok(user),
        None => Err(DbErr::RecordNotFound("user".to_string())),
    }
}

pub async fn get_user_by_account(db: &DatabaseConnection, account: &str) -> Result<Model, DbErr> {
    let user = Entity::find()
        .filter(
            Condition::any()
                .add(Column::Name.eq(account))
                .add(Expr::expr(Func::lower(Expr::col(Column::Email))).eq(account.to_lowercase())),
        )
        .one(db)
        .await?;
    match user {
        Some(user) => Ok(user),
        None => Err(DbErr::RecordNotFound("user".to_string())),
    }
}

pub async fn create_user(db: &DatabaseConnection, user: Model) -> Result<Model, DbErr> {
    let active_model: ActiveModel = ActiveModel {
        id: ActiveValue::NotSet,
        ..user.into_active_model().reset_all()
    };
    active_model.insert(db).await
}

pub async fn count_user(db: &DatabaseConnection) -> Result<u64, DbErr> {
    Entity::find().count(db).await
}

#[cfg(test)]
mod test {
    use sea_orm::IntoActiveModel;

    use super::*;
    #[test]
    fn test_model_transform() {
        let model = Model {
            id: 0,
            name: String::from("Reverier"),
            password: Some(String::from("123456")),
            email: Some(String::from("reverier.xu@woooo.tech")),
            intro: Some(String::from("123456")),
            cover_path: None,
            institute_id: None,
            institute_info: None,
            permissions: Permissions(vec![Permission::Basic]),
            hidden: false,
            banned: false,
        };

        let active_model: ActiveModel = model.clone().into_active_model().reset_all();

        println!("{:?}", active_model);
    }
}
