//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub password: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub intro: Option<String>,
    pub cover_path: Option<String>,
    pub institute_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub institute_info: Option<String>,
    pub level: i32,
    pub hidden: bool,
    pub banned: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::announcement::Entity")]
    Announcement,
    #[sea_orm(has_many = "super::answer::Entity")]
    Answer,
    #[sea_orm(has_many = "super::ctftime::Entity")]
    Ctftime,
    #[sea_orm(has_many = "super::instance::Entity")]
    Instance,
    #[sea_orm(
        belongs_to = "super::institute::Entity",
        from = "Column::InstituteId",
        to = "super::institute::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Institute,
    #[sea_orm(has_many = "super::media::Entity")]
    Media,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
    #[sea_orm(has_many = "super::user2_ip_address::Entity")]
    User2IpAddress,
    #[sea_orm(has_many = "super::user2_subscription::Entity")]
    User2Subscription,
    #[sea_orm(has_many = "super::user2_team::Entity")]
    User2Team,
    #[sea_orm(has_many = "super::wiki::Entity")]
    Wiki,
    #[sea_orm(has_many = "super::write_up::Entity")]
    WriteUp,
}

impl Related<super::announcement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Announcement.def()
    }
}

impl Related<super::answer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Answer.def()
    }
}

impl Related<super::ctftime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ctftime.def()
    }
}

impl Related<super::instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instance.def()
    }
}

impl Related<super::institute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institute.def()
    }
}

impl Related<super::media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Media.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl Related<super::user2_ip_address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2IpAddress.def()
    }
}

impl Related<super::user2_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Subscription.def()
    }
}

impl Related<super::user2_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Team.def()
    }
}

impl Related<super::wiki::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wiki.def()
    }
}

impl Related<super::write_up::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WriteUp.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
