//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use sea_orm::{ActiveValue, IntoActiveModel, Iterable, QueryOrder, QuerySelect};

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wiki")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub published_at: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub updated_at: DateTime<Utc>,
    pub author_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub content: Option<String>,
    pub parent: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::AuthorId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_wiki_page(
    conn: &DatabaseConnection,
    parent: Option<i64>,
) -> Result<Vec<Model>, DbErr> {
    let mut sql = Entity::find()
        .select_only()
        .columns(Column::iter().filter(|c| !matches!(c, Column::Content)))
        .order_by_asc(Column::UpdatedAt);
    if let Some(parent) = parent {
        sql = sql.filter(Column::Parent.eq(parent));
    } else {
        sql = sql.filter(Column::Parent.is_null());
    }
    sql.all(conn).await
}

pub async fn create_wiki(conn: &DatabaseConnection, wiki: Model) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        updated_at: ActiveValue::NotSet,
        published_at: ActiveValue::Set(Utc::now()),
        ..wiki.into_active_model().reset_all()
    };
    active_model.insert(conn).await
}

pub async fn update_wiki(conn: &DatabaseConnection, id: i64, wiki: Model) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::Unchanged(id),
        updated_at: ActiveValue::Set(Utc::now()),
        published_at: ActiveValue::Unchanged(wiki.published_at),
        ..wiki.into_active_model().reset_all()
    };
    active_model.update(conn).await
}

pub async fn delete_wiki(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(conn).await.map(|_| ())
}

pub async fn get_wiki_by_id(conn: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(id).one(conn).await
}
