//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wiki_related")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub wiki_id: i64,
    pub related_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wiki::Entity",
        from = "Column::RelatedId",
        to = "super::wiki::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Wiki2,
    #[sea_orm(
        belongs_to = "super::wiki::Entity",
        from = "Column::WikiId",
        to = "super::wiki::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Wiki1,
}

impl ActiveModelBehavior for ActiveModel {}
