//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use sea_orm::{ActiveValue, Iterable, QuerySelect};

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wiki")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub published_at: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub updated_at: DateTime<Utc>,
    pub author_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub content: Option<String>,
    pub parent: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::AuthorId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_wiki_page(
    conn: &DatabaseConnection,
    parent: Option<i64>,
    page: u64,
    per_page: u64,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find()
        .select_only()
        .columns(Column::iter().filter(|c| !matches!(c, Column::Content)));
    if parent.is_some() {
        sql = sql.filter(Column::Parent.eq(parent.unwrap()));
    }
    let paginator = sql.into_model().paginate(conn, per_page);
    let num_pages = paginator.num_pages().await?;
    let announcements = paginator.fetch_page(page - 1).await?;
    Ok((announcements, num_pages))
}

pub async fn create_wiki(conn: &DatabaseConnection, wiki: Model) -> Result<Model, DbErr> {
    let mut active_model: ActiveModel = wiki.into();
    active_model.id = ActiveValue::NotSet;
    active_model.published_at = ActiveValue::Set(Utc::now());
    active_model.updated_at = ActiveValue::Set(Utc::now());
    active_model.insert(conn).await
}

pub async fn update_wiki(conn: &DatabaseConnection, id: i64, wiki: Model) -> Result<Model, DbErr> {
    let mut active_model: ActiveModel = wiki.clone().into();
    active_model.id = ActiveValue::Unchanged(id);
    active_model.published_at = ActiveValue::Unchanged(wiki.published_at);
    active_model.updated_at = ActiveValue::Set(Utc::now());
    active_model.content = ActiveValue::Set(wiki.content);
    active_model.parent = ActiveValue::Set(wiki.parent);
    active_model.author_id = ActiveValue::Set(wiki.author_id);
    active_model.title = ActiveValue::Set(wiki.title);
    active_model.update(conn).await
}

pub async fn delete_wiki(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(conn).await.map(|_| ())
}

pub async fn get_wiki_by_id(conn: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(id).one(conn).await
}
