//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::{entity::prelude::*, ActiveValue, QuerySelect};
use sea_query::Condition;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wiki_related")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub wiki_id: i64,
    pub related_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wiki::Entity",
        from = "Column::RelatedId",
        to = "super::wiki::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Wiki2,
    #[sea_orm(
        belongs_to = "super::wiki::Entity",
        from = "Column::WikiId",
        to = "super::wiki::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Wiki1,
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_related_wiki_by_wiki_id(
    conn: &DatabaseConnection,
    wiki_id: i64,
) -> Result<(Vec<Model>, u64), DbErr> {
    let sql = Entity::find().filter(
        Condition::any()
            .add(Column::WikiId.eq(wiki_id))
            .add(Column::RelatedId.eq(wiki_id)),
    );
    let total = sql.clone().count(conn).await?;
    let wikis = sql.all(conn).await?;
    Ok((wikis, total))
}

pub async fn add_related_record(
    conn: &DatabaseConnection,
    related_wiki_record: Model,
) -> Result<(), DbErr> {
    match get_record_id_by_wiki_id_and_related_id(
        conn,
        related_wiki_record.wiki_id,
        related_wiki_record.related_id,
    )
    .await?
    {
        Some(_) => Err(DbErr::RecordNotUpdated),
        None => {
            let mut active_model: ActiveModel = related_wiki_record.clone().into();
            active_model.id = ActiveValue::NotSet;
            active_model.insert(conn).await.map(|_| ())
        }
    }
}

pub async fn delete_related_record(
    conn: &DatabaseConnection,
    related_wiki_record: Model,
) -> Result<(), DbErr> {
    match get_record_id_by_wiki_id_and_related_id(
        conn,
        related_wiki_record.wiki_id,
        related_wiki_record.related_id,
    )
    .await?
    {
        Some(id) => Entity::delete_by_id(id).exec(conn).await.map(|_| ()),
        None => Err(DbErr::RecordNotFound(
            "related wiki record not found".to_owned(),
        )),
    }
}

async fn get_record_id_by_wiki_id_and_related_id(
    conn: &DatabaseConnection,
    wiki_id: i64,
    related_id: i64,
) -> Result<Option<i64>, DbErr> {
    let model = Entity::find()
        .select_only()
        .column(Column::Id)
        .filter(
            Condition::any()
                .add(
                    Condition::all()
                        .add(Column::WikiId.eq(wiki_id))
                        .add(Column::RelatedId.eq(related_id)),
                )
                .add(
                    Condition::all()
                        .add(Column::WikiId.eq(related_id))
                        .add(Column::RelatedId.eq(wiki_id)),
                ),
        )
        .one(conn)
        .await?;
    if let Some(model) = model {
        Ok(Some(model.id))
    } else {
        Ok(None)
    }
}
