//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use sea_orm::{ActiveValue, IntoActiveModel, Iterable, QueryOrder, QuerySelect};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "write_up")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub published_at: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub updated_at: DateTime<Utc>,
    pub author_id: Option<i64>,
    pub game_id: i64,
    pub hidden: bool,
    #[sea_orm(column_type = "Text")]
    pub content: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::AuthorId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_writeup_page(
    conn: &DatabaseConnection,
    game_id: i64,
    show_hidden: bool,
    page: u64,
    per_page: u64,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find()
        .select_only()
        .filter(Column::GameId.eq(game_id))
        .columns(Column::iter().filter(|c| !matches!(c, Column::Content)))
        .order_by_desc(Column::PublishedAt);
    if !show_hidden {
        sql = sql.filter(Column::Hidden.eq(false))
    }
    let paginator = sql.into_model().paginate(conn, per_page);
    let num_pages = paginator.num_pages().await?;
    let writeups: Vec<Model> = paginator.fetch_page(page - 1).await?;
    Ok((writeups, num_pages))
}

pub async fn get_writeup(conn: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
    let writeup = Entity::find_by_id(id).one(conn).await?;
    match writeup {
        Some(writeup) => match writeup.hidden {
            true => Err(DbErr::RecordNotFound("writeup".to_string())),
            false => Ok(Some(writeup)),
        },
        None => Err(DbErr::RecordNotFound("writeup".to_string())),
    }
}

pub async fn get_writeup_by_game_and_user_id(
    conn: &DatabaseConnection,
    game_id: i64,
    user_id: i64,
) -> Result<Option<Model>, DbErr> {
    Entity::find()
        .filter(Column::GameId.eq(game_id))
        .filter(Column::AuthorId.eq(user_id))
        .one(conn)
        .await
}

pub async fn create_writeup(
    conn: &DatabaseConnection,
    user_id: i64,
    game_id: i64,
    writeup: Model,
) -> Result<Model, DbErr> {
    if let Ok(Some(_)) = get_writeup_by_game_and_user_id(conn, game_id, user_id).await {
        return Err(DbErr::RecordNotInserted);
    }
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        published_at: ActiveValue::Set(Utc::now()),
        updated_at: ActiveValue::Set(Utc::now()),
        hidden: ActiveValue::Set(true),
        author_id: ActiveValue::Set(Some(user_id)),
        game_id: ActiveValue::Set(game_id),
        ..writeup.into_active_model().reset_all()
    };
    active_model.insert(conn).await
}

pub async fn update_writeup(
    conn: &DatabaseConnection,
    id: i64,
    game_id: i64,
    writeup: Model,
) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::Unchanged(id),
        game_id: ActiveValue::Unchanged(game_id),
        published_at: ActiveValue::NotSet,
        updated_at: ActiveValue::Set(Utc::now()),
        hidden: ActiveValue::NotSet,
        author_id: ActiveValue::NotSet,
        ..writeup.into_active_model().reset_all()
    };
    active_model.update(conn).await
}

pub async fn audit_writeup(conn: &DatabaseConnection, id: i64, hidden: bool) -> Result<(), DbErr> {
    if let Some(writeup) = get_writeup(conn, id).await? {
        let mut active_model: ActiveModel = writeup.into();
        active_model.hidden = ActiveValue::Set(hidden);
        active_model.update(conn).await.map(|_| ())
    } else {
        Err(DbErr::RecordNotFound("writeup".to_string()))
    }
}

pub async fn delete_writeup_by_game_and_user_id(
    conn: &DatabaseConnection,
    game_id: i64,
    user_id: i64,
) -> Result<(), DbErr> {
    match get_writeup_by_game_and_user_id(conn, game_id, user_id).await {
        Ok(Some(writeup)) => Entity::delete_by_id(writeup.id)
            .exec(conn)
            .await
            .map(|_| ()),
        Ok(None) => Err(DbErr::RecordNotFound("writeup".to_string())),
        Err(e) => Err(e),
    }
}
