apiVersion: apps/v1
kind: Deployment
metadata:
  name: ret2shell
  labels:
    app: ret2shell
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ret2shell
  template:
    metadata:
      labels:
        app: ret2shell
    spec:
      containers:
      - name: ret2shell
        image: ret2shell:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "0.5"
            memory: "1024Mi"
