FROM rust:1-alpine as builder

# Do not copy `target` directory by accident.
WORKDIR /usr/ret2shell
COPY src src
COPY Cargo.toml ./
RUN ls && cargo build --release

FROM debian:12

## For developers in China ##
#RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
#RUN sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/ret2shell/target/release/ret2shell /usr/local/bin/ret2shell

CMD ["/usr/local/bin/ret2shell", "up"]
