# [Choice] Debian OS version (use bullseye on local arm64/Apple Silicon): buster, bullseye
ARG VARIANT="bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/rust:1-${VARIANT}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    ca-certificates curl wget \
    musl-dev musl-tools \
    libc6-dev g++ gcc gdb make \
    nodejs zip unzip

RUN corepack enable pnpm
RUN rustup component add clippy
RUN rustup toolchain install nightly
# RUN rustup default nightly
