# Auditor config, for team name auditing.
[auditor]
# the sensitive word list file path
sensitive_word_list = './config/sensitive_word_list.txt'

# Auth config, recommended to replace the signing_key with a random string, such as UUID/nanoid.
[auth]
buffer_time  = 21600              # token will be re-distributed before it expires
expires_time = 86400              # token will expire after this time
signing_key  = 'K3yInD3v3l0pm3nt' # the key to sign the token

# OAuth2 config
[auth.oauth_keys]
#xdu_cas = { id = "https://ctf.xidian.edu.cn/account/oauth", key = "NOTNEEDED" }

# Bucket config, for game/challenge file storage.
[bucket]
path = './data/bucket'

# Cache config
[cache]
# Cluster supports here.
# redis://username:password@foo.com:6379/1
# rediss://username:password@foo.com:6379/1
# redis-cluster://username:password@foo.com:30001?node=bar.com:30002&node=baz.com:30003
# redis-sentinel://username:password@foo.com:6379/1?sentinelServiceName=fakename&node=foo.com:30001&node=bar.com:30002
url = 'redis://localhost:6379'

[captcha]
difficulty = 4
enabled    = true
validator  = 'pow'

[cluster]
auto_infer        = true
capture_directory = "./data/captures"
cleanup_interval  = 60                # in seconds
enable_capture    = true              # currently not working
enabled           = true
kube_config_path  = "~/.kube/config"
node_selector     = "challenge"       # default node selector for challenges, could be specified in each game.
try_default       = false
# deprecated, please use runtime config in the admin panel.
#traffic          = "pub async fn expose(node, service) { Ok(()) }"

[cluster.registry]
# external is used for k8s pulling
external = "ctf.xidian.edu.cn"
insecure = false
# server is used for platform pushing
server = "ctf.xidian.edu.cn"
#username =
#password =

[database]
db       = 'ret2shell'
host     = '127.0.0.1'
password = 'P@ssw02dInD3v3l0pm3nt'
port     = 5432
ssl_mode = 'disable'               # disable, allow, prefer, require, verify-ca, verify-full
user     = 'ret2shell'

[email]
enabled  = false
host     = 'smtp.example.com'
password = 'P@ssw0rdInD3v3l0pm3nt'
port     = 587
sender   = 'Ret2Shell'
tls      = 'starttls'              #  'none' | 'tls' | 'starttls'
username = 'dev@ret.sh.cn'

[logging]
compress   = true
directory  = './data/log'
files_kept = 3
level      = 'info,tower_http=info,sqlx=warn'

[media]
anti_theft = true
limit      = 50             # one user could upload per week
path       = './data/media'

[queue]
host = '127.0.0.1'
port = 4222
### token has higher priority than user & password, only one auth method will be used.
#token = 'T0k3nInD3v3l0pm3nt'
### user and password must be both valid, whether it will be ignored.
#user = 'ret2shell'
#password = 'P@ssw0rdInD3v3l0pm3nt'
#ping_interval = 5
#tls = false

[server]
api_base_path   = '/api'
api_rate_limit  = 10              # in 5 seconds
cors_origins    = '*'
external_domain = 'dev.ret.sh.cn'
external_https  = true
host            = '127.0.0.1'
port            = 8080

### the Following settings could be changed at web admin panel.
### configuration in database will overwrite the following settings.
# name = 'Ret2Shell'
# footer_info = 'Ret 2 Shell'
# footer_url = 'https://github.com/ret2shell/ret2shell'
# subject_info = 'Fight for all the beauty in the world.'
# subject_url = 'https://ret.sh.cn/'
# record = '豫ICP备xxxxxxxx号-1'   # China ICP record
# hide_maker = false

[server.frontend]
path       = './frontend/dist'
serve_type = 'static'          # static | proxy
