apiVersion: v1
kind: Service
metadata:
  name: ret2shell-platform
  namespace: ret2shell-platform
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30307
  selector:
    ret.sh.cn/workload: platform

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ret2shell-platform-data-claim
  namespace: ret2shell-platform
spec:
  storageClassName: ret2shell-storage-platform
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 420Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ret2shell-platform
  namespace: ret2shell-platform
  labels:
    ret.sh.cn/workload: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      ret.sh.cn/workload: platform
  template:
    metadata:
      labels:
        ret.sh.cn/workload: platform
    spec:
      serviceAccountName: ret2shell-service
      containers:
        - name: ret2shell-platform
          image: ghcr.io/ret2shell/ret2shell:latest
          imagePullPolicy: Always
          command: ["/bin/r2s-server"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ret2shell-platform-data
              mountPath: /var/lib/ret2shell/
            - name: ret2shell-platform-config
              mountPath: /etc/ret2shell/config.toml
              readOnly: true
              subPath: config.toml
            - name: ret2shell-platform-blocked
              mountPath: /etc/ret2shell/blocked.txt
              readOnly: true
              subPath: blocked.txt
            - name: ret2shell-platform-license
              mountPath: /etc/ret2shell/license
              readOnly: true
              subPath: license
      volumes:
        - name: ret2shell-platform-data
          persistentVolumeClaim:
            claimName: ret2shell-platform-data-claim
        - name: ret2shell-platform-config
          configMap:
            name: ret2shell-config
        - name: ret2shell-platform-blocked
          configMap:
            name: ret2shell-blocked
        - name: ret2shell-platform-license
          configMap:
            name: ret2shell-license
