<script lang="ts">
  export let width = 256
  export let height = 256
</script>

<svg xmlns="http://www.w3.org/2000/svg" version="1.1" {width} {height} viewBox="0 0 256 256">
  <g>
    <path
      fill="#0078D6"
      stroke="#0078D6"
      stroke-width="6.19649"
      stroke-dasharray="none"
      stroke-opacity="0.564706"
      d="m84.598 189.653-67.953-39.805v-12.37l57.14-32.885 6.491 9.052-52.757 30.017 60.575 35.759zm97.62-6.915-6.494-9.056 52.757-30.017-29.51-16.792 9.634-5.714 30.75 16.32v12.373z"
      class="svg-elem-1"
    ></path>
    <path
      fill="#D60000"
      stroke="#ff0101"
      stroke-width="3.82232"
      stroke-dasharray="none"
      stroke-opacity="0.564706"
      d="m99.331 76.984 37.088 62.889 23.56-22.568 29.018 4.318 35.858-18.537-24.673-61.7-23.207 34.66-54.136-24.982Z"
      class="svg-elem-2"
    ></path>
    <path
      d="M160.25 218.864 85.98 93.034l8.822-9.267 78.154 132.406Z"
      fill="gray"
      stroke="gray"
      stroke-width="5.99999"
      stroke-dasharray="none"
      stroke-opacity=".564706"
      class="svg-elem-3"
    ></path>
    <path
      d="m82.317 86.69 8.764-9.955-6.977-12.503-8.578 11.36z"
      fill="gray"
      stroke="gray"
      stroke-width="5.99999"
      stroke-dasharray="none"
      stroke-opacity=".564706"
      class="svg-elem-4"
    ></path>
  </g>
</svg>

<style lang="scss">
  /***************************************************
 * Generated by SVG Artista on 10/12/2023, 4:02:58 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

  @-webkit-keyframes animate-svg-stroke-1 {
    0% {
      stroke-dashoffset: 542.1497802734375px;
      stroke-dasharray: 542.1497802734375px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 542.1497802734375px;
    }
  }

  @keyframes animate-svg-stroke-1 {
    0% {
      stroke-dashoffset: 542.1497802734375px;
      stroke-dasharray: 542.1497802734375px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 542.1497802734375px;
    }
  }

  @-webkit-keyframes animate-svg-fill-1 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(0, 120, 214);
    }
  }

  @keyframes animate-svg-fill-1 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(0, 120, 214);
    }
  }

  .svg-elem-1 {
    -webkit-animation:
      animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
      animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
    animation:
      animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
      animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
  }

  @-webkit-keyframes animate-svg-stroke-2 {
    0% {
      stroke-dashoffset: 380.1159973144531px;
      stroke-dasharray: 380.1159973144531px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 380.1159973144531px;
    }
  }

  @keyframes animate-svg-stroke-2 {
    0% {
      stroke-dashoffset: 380.1159973144531px;
      stroke-dasharray: 380.1159973144531px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 380.1159973144531px;
    }
  }

  @-webkit-keyframes animate-svg-fill-2 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(214, 0, 0);
    }
  }

  @keyframes animate-svg-fill-2 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(214, 0, 0);
    }
  }

  .svg-elem-2 {
    -webkit-animation:
      animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
      animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
    animation:
      animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
      animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
  }

  @-webkit-keyframes animate-svg-stroke-3 {
    0% {
      stroke-dashoffset: 327.6473693847656px;
      stroke-dasharray: 327.6473693847656px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 327.6473693847656px;
    }
  }

  @keyframes animate-svg-stroke-3 {
    0% {
      stroke-dashoffset: 327.6473693847656px;
      stroke-dasharray: 327.6473693847656px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 327.6473693847656px;
    }
  }

  @-webkit-keyframes animate-svg-fill-3 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(128, 128, 128);
    }
  }

  @keyframes animate-svg-fill-3 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(128, 128, 128);
    }
  }

  .svg-elem-3 {
    -webkit-animation:
      animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
      animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
    animation:
      animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
      animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
  }

  @-webkit-keyframes animate-svg-stroke-4 {
    0% {
      stroke-dashoffset: 56.82680892944336px;
      stroke-dasharray: 56.82680892944336px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 56.82680892944336px;
    }
  }

  @keyframes animate-svg-stroke-4 {
    0% {
      stroke-dashoffset: 56.82680892944336px;
      stroke-dasharray: 56.82680892944336px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 56.82680892944336px;
    }
  }

  @-webkit-keyframes animate-svg-fill-4 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(128, 128, 128);
    }
  }

  @keyframes animate-svg-fill-4 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(128, 128, 128);
    }
  }

  .svg-elem-4 {
    -webkit-animation:
      animate-svg-stroke-4 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
      animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
    animation:
      animate-svg-stroke-4 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
      animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
  }
</style>
