apiVersion: v1
kind: Namespace
metadata:
  name: ret2shell-challenge

---
apiVersion: v1
kind: Namespace
metadata:
  name: ret2shell-platform

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ret2shell-service
  namespace: ret2shell-platform
rules:
  - apiGroups:
      - ''
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - networking.k8s.io
      # - rbac.authorization.k8s.io
    resources:
      - pods
      - pods/portforward
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - networkpolicies
      - endpoints
      # - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      # - persistentvolumes
      # - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      # - serviceaccounts
      - services
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ret2shell-service
  namespace: ret2shell-platform

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ret2shell-service-global
subjects:
  - kind: ServiceAccount
    name: ret2shell-service
    namespace: ret2shell-platform
roleRef:
  kind: ClusterRole
  name: ret2shell-service
  apiGroup: rbac.authorization.k8s.io

