name: Script Image

on:
  push:
    paths:
      - ".github/workflows/scripts.release-image.yml"
      - "Containerfile"
      - "release-image.fish"
      - "release-image.sh"

  workflow_dispatch:

jobs:
  # Only test the release-image script
  image:
    name: ${{ matrix.steps.script }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        steps:
          - shell: fish
            script: release-image.fish
          - shell: sh
            script: release-image.sh

    steps:
      - uses: actions/checkout@v6
        with:
          # fetch depth 0 to fetch all history for git-restore-mtime-action
          fetch-depth: 0

      - uses: chetan/git-restore-mtime-action@v2

      - name: Test ${{ matrix.steps.script }}
        run: ${{ matrix.steps.shell }} '${{ matrix.steps.script }}'
